### ISSUE TITLE
pillar.example failing to compile

### ISSUE THREAD

**Issue by eadderley-tc** [mitodl/fluentd-formula#18]
The pillar.example doesn't seem valid, in particular
```
fluentd:
  configs:
    - name: elasticsearch
      settings:
        - directive: source
          attrs:
            - '@type': syslog
            - port: 514
            - tag: syslog
        - directive: match
          directive_arg: 'syslog.*'
          attrs:
            - '@type': copy
            - nested_directives:
                - directive: store
                  attrs:
                    - '@type': stdout
                - directive: store
                  attrs:
                    - '@type': elasticsearch
                    - logstash_format: true
                    - flush_interval: 10s
                    - host: localhost
                    - port: 9200
```

It throws 
```
fluentd01.novalocal:
    Data failed to compile:
----------
    Rendering SLS 'lab_k8s_eadderley:fluentd.config' failed: Jinja variable 'list object' has no attribute 'items'
```
I'm a novice at all this and having trouble debugging the exact issue.
